defaults: &defaults
  url_rss: 'https://pip.ipex.it/PipWa/Front/GetAcerFeedsPower'
  url_xml: 'https://pip.ipex.it/PipWa/Front/GetXmlStream' 
  mapbox: 'https://api.mapbox.com/datasets/v1/browserino/cjaoj0nr54iq92wlosvaaki0y/features?access_token=sk.eyJ1IjoiYnJvd3NlcmlubyIsImEiOiJjamEzdjBxOGM5Nm85MzNxdG9mOTdnaDQ0In0.tMMxfE2W6-WCYIRzBmCVKg'
  mail:
    from: 'michele.boscolo@eni.com'
    to: 'michele.boscolo@eni.com'
    server: 'relay.eni.pri'
    port: 25
   
development:
  <<: *defaults
  database:
    name: 'Ampere'
    collection: 'remit_centrali'
    collection_centrali_hourly_tecologia: 'remit_centrali_hourly_tecologia'
    collection_centrali_daily_tecologia: 'remit_centrali_daily_tecologia'
    collection_centrali_hourly_zona: 'remit_centrali_hourly_zona'
    collection_centrali_daily_zona: 'remit_centrali_daily_zona'
    collection_centrali_last_daily: 'remit_centrali_last_daily'
    adress: '127.0.0.1:27030'
    log_level: "::Logger::INFO"
  path:
    file_dt_upd: './lastupdate_dev'
    file_csv: './csv/remit.csv'
    csv_esporta: './csv/export.csv'
    download: './download_dev/'

test:
  <<: *defaults

production:
  <<: *defaults
  database:
    name: 'Ampere'
    collection: 'remit_centrali'
    collection_centrali_hourly_tecologia: 'remit_centrali_hourly_tecologia'
    collection_centrali_daily_tecologia: 'remit_centrali_daily_tecologia'
    collection_centrali_hourly_zona: 'remit_centrali_hourly_zona'
    collection_centrali_daily_zona: 'remit_centrali_daily_zona'
    collection_centrali_last_daily: 'remit_centrali_last_daily'
    adress1: '10.130.96.220:27018'
    adress2: '10.130.96.220:27019'
    adress3: '10.130.96.144:27018'
    log_level: "::Logger::INFO"
  path:
    file_dt_upd: './lastupdate'
    file_csv: './csv/remit.csv'
    csv_esporta: './csv/export.csv'
    download: './download/'


