defaults: &defaults
  site: 'https://pip.ipex.it/PipWa/Front/GetAcerFeedsPower'
  mapbox: 'https://api.mapbox.com/datasets/v1/browserino/cjaoj0nr54iq92wlosvaaki0y/features?access_token=sk.eyJ1IjoiYnJvd3NlcmlubyIsImEiOiJjamEzdjBxOGM5Nm85MzNxdG9mOTdnaDQ0In0.tMMxfE2W6-WCYIRzBmCVKg'
  mail:
    from: 'michele.boscolo@eni.com'
    to: 'michele.boscolo@eni.com'
    server: 'relay.eni.pri'
    port: 25
   
development:
  <<: *defaults
  database:
    name: 'transmission'
    collection: 'remit_centrali'
    collection_last: 'remit_centrali_last'
    adress: '127.0.0.1:27030'
    log_level: "::Logger::INFO"
  path:
    file_dt_upd: './lastupdate_dev'
    file_csv: './csv/remit.csv'
    csv_esporta: './csv/export.csv'

test:
  <<: *defaults

production:
  <<: *defaults
  database:
    name: 'transmission'
    collection: 'remit_centrali'
    adress1: '10.130.96.220:27018'
    adress2: '10.130.96.220:27019'
    adress3: '10.130.96.144:27018'
    log_level: "::Logger::INFO"
  path:
    file_dt_upd: './lastupdate'
    file_csv: './csv/remit.csv'
    csv_esporta: './csv/export.csv'


